# Generated by Django 3.0.5 on 2020-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=1000)),
                ('hotel_id', models.CharField(max_length=250)),
                ('postal_code', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'HotelBooking',
                'verbose_name_plural': 'HotelBookings',
            },
        ),
    ]
