# Generated by Django 3.0.5 on 2020-05-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
