# Generated by Django 3.0.5 on 2020-05-06 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200506_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
