# Generated by Django 3.0.5 on 2020-05-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hotelbooking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='phone_number',
        ),
    ]
