# Generated by Django 3.0.5 on 2020-05-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200506_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='hotel_id',
            new_name='property_id',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='hotel_name',
            new_name='property_name',
        ),
    ]
